In [1]:
import numpy as np


In [8]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a[1:3]

array([2, 3])

In [13]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [15]:
a[0:2,:]

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [18]:
for nu in a:
    print(nu)

[1 2 3]
[2 3 4]
[4 5 6]


In [20]:
for nu in a.flat:
    print(nu,end=' ')

1 2 3 2 3 4 4 5 6 

In [25]:
a=np.arange(6).reshape(2,3)
print(a)
b=np.arange(6,12).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [26]:
p=a+b
print(p)

[[ 6  8 10]
 [12 14 16]]


In [28]:
aw=np.vstack((a,b))
aw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [31]:
k=np.arange(10,30).reshape(4,5)
k

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
k=np.arange(10,40).reshape(2,15)
k

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [39]:
np.hsplit(k,3)

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]]), array([[15, 16, 17, 18, 19],
        [30, 31, 32, 33, 34]]), array([[20, 21, 22, 23, 24],
        [35, 36, 37, 38, 39]])]

In [45]:
t=np.hsplit(k,3)
print(t[0],'\n')
print(t[1],'\n')
print(t[2])

[[10 11 12 13 14]
 [25 26 27 28 29]] 

[[15 16 17 18 19]
 [30 31 32 33 34]] 

[[20 21 22 23 24]
 [35 36 37 38 39]]


In [48]:
np.vsplit(k,2)

[array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [49]:
p=np.vsplit(k,2)

In [50]:
p[0]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
p[1]

array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [53]:
aw=np.arange(10,30).reshape(4,5)
aw

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [54]:
b=aw>15
print(b)

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [58]:
aw[b]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
aw[b]=1
aw

array([[10, 11, 12, 13, 14],
       [15,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1]])

In [61]:
end='thnqu'
end

'thnqu'