In [1]:
import numpy as np

In [10]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
z=np.array([4,5,6,7])
z[2]

6

In [19]:
za=np.array([[1,2],[5,6],[6,7]])
print(za[1])
za.ndim

[5 6]


2

In [26]:
zb=np.array([[2,4],[5,6],[7,8]])
print(za+zb)
zb.itemsize

[[ 3  6]
 [10 12]
 [13 15]]


4

In [36]:
a=np.array([4,5,6,7])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
a=np.array([4,5,6,7],dtype=np.float64)
print(a.dtype)
print(a)
print(a.shape)
d=np.array([[1,2],[4,5],[5,6],[4,3],[2,3]])
print(d)
print(d.shape)
d=np.array([[1,2],[4,5],[5,6],[4,3],[2,3]],dtype=np.complex)
print(d)


[4 5 6 7]
1
4
int32
float64
[4. 5. 6. 7.]
(4,)
[[1 2]
 [4 5]
 [5 6]
 [4 3]
 [2 3]]
(5, 2)
[[1.+0.j 2.+0.j]
 [4.+0.j 5.+0.j]
 [5.+0.j 6.+0.j]
 [4.+0.j 3.+0.j]
 [2.+0.j 3.+0.j]]


In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
l=range(5)
print(l[0])
print(l[1])
print(l[3])
k=np.arange(0,10)
print(k)
w=np.arange(0,10,2)
print(w)


0
1
3
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [50]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [54]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [56]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [82]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [83]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [86]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [93]:
print(a)
#1,2 axis=0 1+2=3
#3,4 3+4=7
#5,6 5+6=11
#axis=1 1+3+5=9 and 2+4+6=12
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 2]
 [3 4]
 [5 6]]
1
6
21
[ 9 12]
[ 3  7 11]


In [97]:
print(a)
print(np.sqrt(a))
print(np.std(a))#standard deviation

[[1 2]
 [3 4]
 [5 6]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


In [110]:
aq=np.array([[1,2],[2,4]])
aw=np.array([[2,3],[4,5]])
print(aq)
print()
print(aw)

[[1 2]
 [2 4]]

[[2 3]
 [4 5]]


In [111]:
print(aq+aw)
print(aq*aw)
print(aq-aw)
print(aq.dot(aw))

[[3 5]
 [6 9]]
[[ 2  6]
 [ 8 20]]
[[-1 -1]
 [-2 -1]]
[[10 13]
 [20 26]]


In [126]:
#222222222222222222222222222222222222222222222222222222222222222222222222222222222222
import numpy as np
a=np.array([[1,2],[2,4],[5,6],[7,8]])
print(a)
print(a[:,1:2])
print(a[3:4,:])

[[1 2]
 [2 4]
 [5 6]
 [7 8]]
[[2]
 [4]
 [6]
 [8]]
[[7 8]]


In [129]:
for e in a:
    print(e)
for e in a.flat:
    print(e,end=' ')

[1 2]
[2 4]
[5 6]
[7 8]
1 2 2 4 5 6 7 8 

In [131]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [132]:
np.vstack((a,b)) #vertical stack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [133]:
np.hstack((a,b)) #horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [135]:
c=np.arange(30).reshape(2,15)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [143]:
result=np.hsplit(c,3)
#print('the whole result is:',result)
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [145]:
result=np.vsplit(c,2)
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [147]:
a=np.arange(12).reshape(3,4)
print(a)
b=a>4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [148]:
print(a[b]) #retur those elemnt which is true and print values of them

[ 5  6  7  8  9 10 11]


In [150]:
a[b]=1
print(a)

[[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [151]:
#3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333

In [152]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [154]:
for i in a:
    print(i)
for i in a:
    for j in i:
        print(j)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [155]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [159]:
print(a)
for x in np.nditer(a,order='C'): printing column wise
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [164]:
print(a)
for x in np.nditer(a,order='F'): #its printing row wise
    print(x)
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [166]:
print(a)
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [169]:
b=np.arange(3,15,4).reshape(3,1)
print(b)

[[ 3]
 [ 7]
 [11]]


In [170]:
#iterating for a ,b both at atime 
for i,j in np.nditer([a,b]):
    print(i,j)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
